In [4]:
import numpy as np

In [21]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
b = np.zeros((3,2))
b[1,:] = a[1,:]
b

array([[0., 0.],
       [3., 4.],
       [0., 0.]])

In [23]:
b[1,0]=1
b

array([[0., 0.],
       [1., 4.],
       [0., 0.]])

In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])